### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by ElBatanony** [TE-Flutter/fan_is_fun#1]
https://pub.dev/packages/flutter_polls

Create a collection for Polls

Each poll would have a list of options and counters for how many voted users.

Another option: Create a collection for votes. Each user would create a vote document when choosing in a poll
The poll would collect all the relevant votes and display them.

**Comment by khlebobul** [comment]
I created a small project for quizzes [(link)](https://github.com/TE-Flutter/quiz-app), I propose to use it, but change the result and output polls using [pool 1.5.1](https://pub.dev/packages/pool)
